on:
  push:
jobs:
  mail_on_push:
  runs-on: ubuntu-latest 
  steps:
    - name: Send email to this address 
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: "ALERT, WE HAVE DETECTED HOT SINGLE COMMITS IN YOUR AREA ${{github.respository}}"
        body: |
          Hello teem,
          A hot single commit has been detectedd in your area. Ples review changes, and merg into main branch.

          Hot single commit commited by: ${{github.event.pusher.name}}
          Changes: 
          to: "mmark.kuusik@gmail.com"
          from: "Github actions for $ {{github.repository}}"